<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-27T16:35:28 IST" name="Suite" finished-at="2022-09-27T16:36:12 IST" duration-ms="43537">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" name="LoginErrorValidation" class="testcase.ErrorValidationsTest"/>
        <method signature="ErrorValidationsTest.ProductCatalogueErrorValidationTest()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" name="ProductCatalogueErrorValidationTest" class="testcase.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="PurchaseProducts">
        <method signature="SubmitOrderTest.SubmitOrderTest(java.util.HashMap)[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" name="SubmitOrderTest" class="testcase.SubmitOrderTest"/>
        <method signature="SubmitOrderTest.OrderHistoryTest()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" name="OrderHistoryTest" class="testcase.SubmitOrderTest"/>
      </group> <!-- PurchaseProducts -->
    </groups>
    <test started-at="2022-09-27T16:35:28 IST" name="Error Validations Test" finished-at="2022-09-27T16:35:57 IST" duration-ms="28621">
      <class name="testcase.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:28 IST" name="launchApplication" finished-at="2022-09-27T16:35:32 IST" duration-ms="3823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:32 IST" name="LoginErrorValidation" finished-at="2022-09-27T16:35:33 IST" duration-ms="914" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email r password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email r password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcase.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:33 IST" name="tearDown" finished-at="2022-09-27T16:35:33 IST" duration-ms="55" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:33 IST" name="launchApplication" finished-at="2022-09-27T16:35:35 IST" duration-ms="1357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:35 IST" name="LoginErrorValidation" finished-at="2022-09-27T16:35:35 IST" duration-ms="874" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email r password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email r password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcase.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:36 IST" name="tearDown" finished-at="2022-09-27T16:35:36 IST" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:36 IST" name="launchApplication" finished-at="2022-09-27T16:35:37 IST" duration-ms="1487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductCatalogueErrorValidationTest()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:37 IST" name="ProductCatalogueErrorValidationTest" finished-at="2022-09-27T16:35:57 IST" duration-ms="19650" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductCatalogueErrorValidationTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ErrorValidationsTest@31c7528f]" started-at="2022-09-27T16:35:57 IST" name="tearDown" finished-at="2022-09-27T16:35:57 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
    <test started-at="2022-09-27T16:35:28 IST" name="Submit Order Test" finished-at="2022-09-27T16:36:12 IST" duration-ms="43537">
      <class name="testcase.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:35:29 IST" name="launchApplication" finished-at="2022-09-27T16:35:32 IST" duration-ms="3868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrderTest(java.util.HashMap)[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:35:32 IST" name="SubmitOrderTest" data-provider="getData" finished-at="2022-09-27T16:35:47 IST" duration-ms="14846" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abhi@12345, email=dasgupta.abhishek0869@gmail.com, productName=zara coat 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrderTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:35:47 IST" name="tearDown" finished-at="2022-09-27T16:35:47 IST" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:35:47 IST" name="launchApplication" finished-at="2022-09-27T16:35:49 IST" duration-ms="1672" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrderTest(java.util.HashMap)[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:35:49 IST" name="SubmitOrderTest" data-provider="getData" finished-at="2022-09-27T16:36:03 IST" duration-ms="14518" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abhi@12345, email=abhi@gmail.com, productName=adidas original}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrderTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:36:03 IST" name="tearDown" finished-at="2022-09-27T16:36:04 IST" duration-ms="62" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:36:04 IST" name="launchApplication" finished-at="2022-09-27T16:36:06 IST" duration-ms="2696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:36:06 IST" name="OrderHistoryTest" finished-at="2022-09-27T16:36:12 IST" depends-on-methods="testcase.SubmitOrderTest.SubmitOrderTest" duration-ms="5547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.SubmitOrderTest@51fadaff]" started-at="2022-09-27T16:36:12 IST" name="tearDown" finished-at="2022-09-27T16:36:12 IST" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
